// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: protos/razpravljalnica.proto

package razpravljalnica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpType int32

const (
	OpType_OP_POST   OpType = 0 // add a message to a topic
	OpType_OP_LIKE   OpType = 1 // like a message
	OpType_OP_DELETE OpType = 2 // delete a message
	OpType_OP_UPDATE OpType = 3 // update a message
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_POST",
		1: "OP_LIKE",
		2: "OP_DELETE",
		3: "OP_UPDATE",
	}
	OpType_value = map[string]int32{
		"OP_POST":   0,
		"OP_LIKE":   1,
		"OP_DELETE": 2,
		"OP_UPDATE": 3,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_razpravljalnica_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_protos_razpravljalnica_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

type ChainRole int32

const (
	ChainRole_ROLE_UNKNOWN ChainRole = 0
	ChainRole_ROLE_HEAD    ChainRole = 1
	ChainRole_ROLE_MIDDLE  ChainRole = 2
	ChainRole_ROLE_TAIL    ChainRole = 3
)

// Enum value maps for ChainRole.
var (
	ChainRole_name = map[int32]string{
		0: "ROLE_UNKNOWN",
		1: "ROLE_HEAD",
		2: "ROLE_MIDDLE",
		3: "ROLE_TAIL",
	}
	ChainRole_value = map[string]int32{
		"ROLE_UNKNOWN": 0,
		"ROLE_HEAD":    1,
		"ROLE_MIDDLE":  2,
		"ROLE_TAIL":    3,
	}
)

func (x ChainRole) Enum() *ChainRole {
	p := new(ChainRole)
	*p = x
	return p
}

func (x ChainRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainRole) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_razpravljalnica_proto_enumTypes[1].Descriptor()
}

func (ChainRole) Type() protoreflect.EnumType {
	return &file_protos_razpravljalnica_proto_enumTypes[1]
}

func (x ChainRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainRole.Descriptor instead.
func (ChainRole) EnumDescriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{1}
}

// //////////////////////////////////////////////////////////////////////////////
// Basic data types
// //////////////////////////////////////////////////////////////////////////////
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{1}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Likes         int32                  `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Message) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user who liked the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{3}
}

func (x *Like) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Like) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Like) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotency key; client should reuse on retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotency key; client should reuse on retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTopicRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotency key; client should reuse on retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{7}
}

func (x *PostMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *PostMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PostMessageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotency key; client should reuse on retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *DeleteMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *DeleteMessageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type UpdateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`                            // new text
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotency key; client should reuse on retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *UpdateMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UpdateMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateMessageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type LikeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // user who posted the like
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotency key; client should reuse on retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeMessageRequest) Reset() {
	*x = LikeMessageRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeMessageRequest) ProtoMessage() {}

func (x *LikeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeMessageRequest.ProtoReflect.Descriptor instead.
func (*LikeMessageRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{10}
}

func (x *LikeMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *LikeMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LikeMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeMessageRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{11}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	FromMessageId int64                  `protobuf:"varint,2,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"` // starting id of the message (0 from beggining)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                        // max number of messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{12}
}

func (x *GetMessagesRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *GetMessagesRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{13}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SubscribeTopicRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TopicId        []int64                `protobuf:"varint,1,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromMessageId  int64                  `protobuf:"varint,3,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"` // starting id of the message
	SubscribeToken string                 `protobuf:"bytes,4,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // token generated by the head used to authorize the subscription
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeTopicRequest) Reset() {
	*x = SubscribeTopicRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicRequest) ProtoMessage() {}

func (x *SubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeTopicRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

func (x *SubscribeTopicRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

type SubscriptionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       []int64                `protobuf:"varint,2,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionNodeRequest) Reset() {
	*x = SubscriptionNodeRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeRequest) ProtoMessage() {}

func (x *SubscriptionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{15}
}

func (x *SubscriptionNodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscriptionNodeRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

type SubscriptionNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscribeToken string                 `protobuf:"bytes,1,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // subscription token to be presented to the returned node
	Node           *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionNodeResponse) Reset() {
	*x = SubscriptionNodeResponse{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeResponse) ProtoMessage() {}

func (x *SubscriptionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeResponse) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{16}
}

func (x *SubscriptionNodeResponse) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

func (x *SubscriptionNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type MessageEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // monotonically increasing event number
	Op             OpType                 `protobuf:"varint,2,opt,name=op,proto3,enum=razpravljalnica.OpType" json:"op,omitempty"`                   // type of event
	Message        *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EventAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=event_at,json=eventAt,proto3" json:"event_at,omitempty"` // timestamp of the event
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{17}
}

func (x *MessageEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MessageEvent) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_POST
}

func (x *MessageEvent) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageEvent) GetEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EventAt
	}
	return nil
}

type WatchClusterStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If set, the server may skip sending updates until config_version > last_seen_config_version.
	LastSeenConfigVersion int64 `protobuf:"varint,1,opt,name=last_seen_config_version,json=lastSeenConfigVersion,proto3" json:"last_seen_config_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WatchClusterStateRequest) Reset() {
	*x = WatchClusterStateRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchClusterStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchClusterStateRequest) ProtoMessage() {}

func (x *WatchClusterStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchClusterStateRequest.ProtoReflect.Descriptor instead.
func (*WatchClusterStateRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{18}
}

func (x *WatchClusterStateRequest) GetLastSeenConfigVersion() int64 {
	if x != nil {
		return x.LastSeenConfigVersion
	}
	return 0
}

type GetClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	Chain         []*NodeInfo            `protobuf:"bytes,3,rep,name=chain,proto3" json:"chain,omitempty"` // head..tail (best-effort, for debugging/clients)
	ConfigVersion int64                  `protobuf:"varint,4,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{19}
}

func (x *GetClusterStateResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

func (x *GetClusterStateResponse) GetChain() []*NodeInfo {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *GetClusterStateResponse) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastApplied   int64                  `protobuf:"varint,1,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	LastCommitted int64                  `protobuf:"varint,2,opt,name=last_committed,json=lastCommitted,proto3" json:"last_committed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{20}
}

func (x *NodeStatus) GetLastApplied() int64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *NodeStatus) GetLastCommitted() int64 {
	if x != nil {
		return x.LastCommitted
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // node's advertised gRPC address
	Status        *NodeStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion int64                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Role          ChainRole              `protobuf:"varint,2,opt,name=role,proto3,enum=razpravljalnica.ChainRole" json:"role,omitempty"`
	Head          *NodeInfo              `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,4,opt,name=tail,proto3" json:"tail,omitempty"`
	Predecessor   *NodeInfo              `protobuf:"bytes,5,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	Successor     *NodeInfo              `protobuf:"bytes,6,opt,name=successor,proto3" json:"successor,omitempty"`
	Chain         []*NodeInfo            `protobuf:"bytes,7,rep,name=chain,proto3" json:"chain,omitempty"` // head..tail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{22}
}

func (x *HeartbeatResponse) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *HeartbeatResponse) GetRole() ChainRole {
	if x != nil {
		return x.Role
	}
	return ChainRole_ROLE_UNKNOWN
}

func (x *HeartbeatResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *HeartbeatResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

func (x *HeartbeatResponse) GetPredecessor() *NodeInfo {
	if x != nil {
		return x.Predecessor
	}
	return nil
}

func (x *HeartbeatResponse) GetSuccessor() *NodeInfo {
	if x != nil {
		return x.Successor
	}
	return nil
}

func (x *HeartbeatResponse) GetChain() []*NodeInfo {
	if x != nil {
		return x.Chain
	}
	return nil
}

type AddNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeRequest) Reset() {
	*x = AddNodeRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeRequest) ProtoMessage() {}

func (x *AddNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeRequest.ProtoReflect.Descriptor instead.
func (*AddNodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{23}
}

func (x *AddNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AddNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AddNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentTail   *NodeInfo              `protobuf:"bytes,1,opt,name=current_tail,json=currentTail,proto3" json:"current_tail,omitempty"` // nil if no tail exists yet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodeResponse) Reset() {
	*x = AddNodeResponse{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeResponse) ProtoMessage() {}

func (x *AddNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeResponse.ProtoReflect.Descriptor instead.
func (*AddNodeResponse) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{24}
}

func (x *AddNodeResponse) GetCurrentTail() *NodeInfo {
	if x != nil {
		return x.CurrentTail
	}
	return nil
}

type ActivateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateNodeRequest) Reset() {
	*x = ActivateNodeRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateNodeRequest) ProtoMessage() {}

func (x *ActivateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateNodeRequest.ProtoReflect.Descriptor instead.
func (*ActivateNodeRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{25}
}

func (x *ActivateNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type LogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	RequestId      string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // idempotency key for client retries (assigned/propagated by head)
	At             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	// Types that are valid to be assigned to Op:
	//
	//	*LogEntry_CreateUser
	//	*LogEntry_CreateTopic
	//	*LogEntry_PostMessage
	//	*LogEntry_UpdateMessage
	//	*LogEntry_DeleteMessage
	//	*LogEntry_LikeMessage
	//	*LogEntry_RegisterSubscription
	Op            isLogEntry_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{26}
}

func (x *LogEntry) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *LogEntry) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LogEntry) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *LogEntry) GetOp() isLogEntry_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *LogEntry) GetCreateUser() *CreateUserOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_CreateUser); ok {
			return x.CreateUser
		}
	}
	return nil
}

func (x *LogEntry) GetCreateTopic() *CreateTopicOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_CreateTopic); ok {
			return x.CreateTopic
		}
	}
	return nil
}

func (x *LogEntry) GetPostMessage() *PostMessageOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_PostMessage); ok {
			return x.PostMessage
		}
	}
	return nil
}

func (x *LogEntry) GetUpdateMessage() *UpdateMessageOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_UpdateMessage); ok {
			return x.UpdateMessage
		}
	}
	return nil
}

func (x *LogEntry) GetDeleteMessage() *DeleteMessageOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_DeleteMessage); ok {
			return x.DeleteMessage
		}
	}
	return nil
}

func (x *LogEntry) GetLikeMessage() *LikeMessageOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_LikeMessage); ok {
			return x.LikeMessage
		}
	}
	return nil
}

func (x *LogEntry) GetRegisterSubscription() *RegisterSubscriptionOp {
	if x != nil {
		if x, ok := x.Op.(*LogEntry_RegisterSubscription); ok {
			return x.RegisterSubscription
		}
	}
	return nil
}

type isLogEntry_Op interface {
	isLogEntry_Op()
}

type LogEntry_CreateUser struct {
	CreateUser *CreateUserOp `protobuf:"bytes,10,opt,name=create_user,json=createUser,proto3,oneof"`
}

type LogEntry_CreateTopic struct {
	CreateTopic *CreateTopicOp `protobuf:"bytes,11,opt,name=create_topic,json=createTopic,proto3,oneof"`
}

type LogEntry_PostMessage struct {
	PostMessage *PostMessageOp `protobuf:"bytes,12,opt,name=post_message,json=postMessage,proto3,oneof"`
}

type LogEntry_UpdateMessage struct {
	UpdateMessage *UpdateMessageOp `protobuf:"bytes,13,opt,name=update_message,json=updateMessage,proto3,oneof"`
}

type LogEntry_DeleteMessage struct {
	DeleteMessage *DeleteMessageOp `protobuf:"bytes,14,opt,name=delete_message,json=deleteMessage,proto3,oneof"`
}

type LogEntry_LikeMessage struct {
	LikeMessage *LikeMessageOp `protobuf:"bytes,15,opt,name=like_message,json=likeMessage,proto3,oneof"`
}

type LogEntry_RegisterSubscription struct {
	RegisterSubscription *RegisterSubscriptionOp `protobuf:"bytes,16,opt,name=register_subscription,json=registerSubscription,proto3,oneof"`
}

func (*LogEntry_CreateUser) isLogEntry_Op() {}

func (*LogEntry_CreateTopic) isLogEntry_Op() {}

func (*LogEntry_PostMessage) isLogEntry_Op() {}

func (*LogEntry_UpdateMessage) isLogEntry_Op() {}

func (*LogEntry_DeleteMessage) isLogEntry_Op() {}

func (*LogEntry_LikeMessage) isLogEntry_Op() {}

func (*LogEntry_RegisterSubscription) isLogEntry_Op() {}

type RegisterSubscriptionOp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId        []int64                `protobuf:"varint,3,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	AssignedNodeId string                 `protobuf:"bytes,4,opt,name=assigned_node_id,json=assignedNodeId,proto3" json:"assigned_node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterSubscriptionOp) Reset() {
	*x = RegisterSubscriptionOp{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSubscriptionOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSubscriptionOp) ProtoMessage() {}

func (x *RegisterSubscriptionOp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSubscriptionOp.ProtoReflect.Descriptor instead.
func (*RegisterSubscriptionOp) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{27}
}

func (x *RegisterSubscriptionOp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterSubscriptionOp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterSubscriptionOp) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

func (x *RegisterSubscriptionOp) GetAssignedNodeId() string {
	if x != nil {
		return x.AssignedNodeId
	}
	return ""
}

type CreateUserOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserOp) Reset() {
	*x = CreateUserOp{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserOp) ProtoMessage() {}

func (x *CreateUserOp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserOp.ProtoReflect.Descriptor instead.
func (*CreateUserOp) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{28}
}

func (x *CreateUserOp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateUserOp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTopicOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicOp) Reset() {
	*x = CreateTopicOp{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicOp) ProtoMessage() {}

func (x *CreateTopicOp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicOp.ProtoReflect.Descriptor instead.
func (*CreateTopicOp) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{29}
}

func (x *CreateTopicOp) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *CreateTopicOp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PostMessageOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageOp) Reset() {
	*x = PostMessageOp{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageOp) ProtoMessage() {}

func (x *PostMessageOp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageOp.ProtoReflect.Descriptor instead.
func (*PostMessageOp) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{30}
}

func (x *PostMessageOp) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *PostMessageOp) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *PostMessageOp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostMessageOp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type UpdateMessageOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageOp) Reset() {
	*x = UpdateMessageOp{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageOp) ProtoMessage() {}

func (x *UpdateMessageOp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageOp.ProtoReflect.Descriptor instead.
func (*UpdateMessageOp) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateMessageOp) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *UpdateMessageOp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateMessageOp) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UpdateMessageOp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DeleteMessageOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageOp) Reset() {
	*x = DeleteMessageOp{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageOp) ProtoMessage() {}

func (x *DeleteMessageOp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageOp.ProtoReflect.Descriptor instead.
func (*DeleteMessageOp) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteMessageOp) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *DeleteMessageOp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteMessageOp) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type LikeMessageOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeMessageOp) Reset() {
	*x = LikeMessageOp{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeMessageOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeMessageOp) ProtoMessage() {}

func (x *LikeMessageOp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeMessageOp.ProtoReflect.Descriptor instead.
func (*LikeMessageOp) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{33}
}

func (x *LikeMessageOp) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *LikeMessageOp) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LikeMessageOp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LogEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{34}
}

func (x *ReplicateRequest) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type AckRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{35}
}

func (x *AckRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type GetEntriesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FromSequenceNumber int64                  `protobuf:"varint,1,opt,name=from_sequence_number,json=fromSequenceNumber,proto3" json:"from_sequence_number,omitempty"` // inclusive
	Limit              int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                                       // server may return fewer
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetEntriesRequest) Reset() {
	*x = GetEntriesRequest{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntriesRequest) ProtoMessage() {}

func (x *GetEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetEntriesRequest) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{36}
}

func (x *GetEntriesRequest) GetFromSequenceNumber() int64 {
	if x != nil {
		return x.FromSequenceNumber
	}
	return 0
}

func (x *GetEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntriesResponse) Reset() {
	*x = GetEntriesResponse{}
	mi := &file_protos_razpravljalnica_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntriesResponse) ProtoMessage() {}

func (x *GetEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_razpravljalnica_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetEntriesResponse) Descriptor() ([]byte, []int) {
	return file_protos_razpravljalnica_proto_rawDescGZIP(), []int{37}
}

func (x *GetEntriesResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_protos_razpravljalnica_proto protoreflect.FileDescriptor

const file_protos_razpravljalnica_proto_rawDesc = "" +
	"\n" +
	"\x1cprotos/razpravljalnica.proto\x12\x0frazpravljalnica\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb2\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05likes\x18\x06 \x01(\x05R\x05likes\"Y\n" +
	"\x04Like\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"F\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"G\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"{\n" +
	"\x12PostMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\x88\x01\n" +
	"\x14DeleteMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\x9c\x01\n" +
	"\x14UpdateMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\x86\x01\n" +
	"\x12LikeMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"D\n" +
	"\x12ListTopicsResponse\x12.\n" +
	"\x06topics\x18\x01 \x03(\v2\x16.razpravljalnica.TopicR\x06topics\"m\n" +
	"\x12GetMessagesRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12&\n" +
	"\x0ffrom_message_id\x18\x02 \x01(\x03R\rfromMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"K\n" +
	"\x13GetMessagesResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.razpravljalnica.MessageR\bmessages\"\x9c\x01\n" +
	"\x15SubscribeTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x03(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12&\n" +
	"\x0ffrom_message_id\x18\x03 \x01(\x03R\rfromMessageId\x12'\n" +
	"\x0fsubscribe_token\x18\x04 \x01(\tR\x0esubscribeToken\"M\n" +
	"\x17SubscriptionNodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x02 \x03(\x03R\atopicId\"r\n" +
	"\x18SubscriptionNodeResponse\x12'\n" +
	"\x0fsubscribe_token\x18\x01 \x01(\tR\x0esubscribeToken\x12-\n" +
	"\x04node\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\"\xcb\x01\n" +
	"\fMessageEvent\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x02op\x122\n" +
	"\amessage\x18\x03 \x01(\v2\x18.razpravljalnica.MessageR\amessage\x125\n" +
	"\bevent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventAt\"S\n" +
	"\x18WatchClusterStateRequest\x127\n" +
	"\x18last_seen_config_version\x18\x01 \x01(\x03R\x15lastSeenConfigVersion\"\xcf\x01\n" +
	"\x17GetClusterStateResponse\x12-\n" +
	"\x04head\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04head\x12-\n" +
	"\x04tail\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04tail\x12/\n" +
	"\x05chain\x18\x03 \x03(\v2\x19.razpravljalnica.NodeInfoR\x05chain\x12%\n" +
	"\x0econfig_version\x18\x04 \x01(\x03R\rconfigVersion\"V\n" +
	"\n" +
	"NodeStatus\x12!\n" +
	"\flast_applied\x18\x01 \x01(\x03R\vlastApplied\x12%\n" +
	"\x0elast_committed\x18\x02 \x01(\x03R\rlastCommitted\"z\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x123\n" +
	"\x06status\x18\x03 \x01(\v2\x1b.razpravljalnica.NodeStatusR\x06status\"\xef\x02\n" +
	"\x11HeartbeatResponse\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x03R\rconfigVersion\x12.\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1a.razpravljalnica.ChainRoleR\x04role\x12-\n" +
	"\x04head\x18\x03 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04head\x12-\n" +
	"\x04tail\x18\x04 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04tail\x12;\n" +
	"\vpredecessor\x18\x05 \x01(\v2\x19.razpravljalnica.NodeInfoR\vpredecessor\x127\n" +
	"\tsuccessor\x18\x06 \x01(\v2\x19.razpravljalnica.NodeInfoR\tsuccessor\x12/\n" +
	"\x05chain\x18\a \x03(\v2\x19.razpravljalnica.NodeInfoR\x05chain\"C\n" +
	"\x0eAddNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"O\n" +
	"\x0fAddNodeResponse\x12<\n" +
	"\fcurrent_tail\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\vcurrentTail\".\n" +
	"\x13ActivateNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x8b\x05\n" +
	"\bLogEntry\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12@\n" +
	"\vcreate_user\x18\n" +
	" \x01(\v2\x1d.razpravljalnica.CreateUserOpH\x00R\n" +
	"createUser\x12C\n" +
	"\fcreate_topic\x18\v \x01(\v2\x1e.razpravljalnica.CreateTopicOpH\x00R\vcreateTopic\x12C\n" +
	"\fpost_message\x18\f \x01(\v2\x1e.razpravljalnica.PostMessageOpH\x00R\vpostMessage\x12I\n" +
	"\x0eupdate_message\x18\r \x01(\v2 .razpravljalnica.UpdateMessageOpH\x00R\rupdateMessage\x12I\n" +
	"\x0edelete_message\x18\x0e \x01(\v2 .razpravljalnica.DeleteMessageOpH\x00R\rdeleteMessage\x12C\n" +
	"\flike_message\x18\x0f \x01(\v2\x1e.razpravljalnica.LikeMessageOpH\x00R\vlikeMessage\x12^\n" +
	"\x15register_subscription\x18\x10 \x01(\v2'.razpravljalnica.RegisterSubscriptionOpH\x00R\x14registerSubscriptionB\x04\n" +
	"\x02op\"\x8c\x01\n" +
	"\x16RegisterSubscriptionOp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x03 \x03(\x03R\atopicId\x12(\n" +
	"\x10assigned_node_id\x18\x04 \x01(\tR\x0eassignedNodeId\";\n" +
	"\fCreateUserOp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\">\n" +
	"\rCreateTopicOp\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"v\n" +
	"\rPostMessageOp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"x\n" +
	"\x0fUpdateMessageOp\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"d\n" +
	"\x0fDeleteMessageOp\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\"b\n" +
	"\rLikeMessageOp\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"C\n" +
	"\x10ReplicateRequest\x12/\n" +
	"\x05entry\x18\x01 \x01(\v2\x19.razpravljalnica.LogEntryR\x05entry\"5\n" +
	"\n" +
	"AckRequest\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\"[\n" +
	"\x11GetEntriesRequest\x120\n" +
	"\x14from_sequence_number\x18\x01 \x01(\x03R\x12fromSequenceNumber\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"I\n" +
	"\x12GetEntriesResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.razpravljalnica.LogEntryR\aentries*@\n" +
	"\x06OpType\x12\v\n" +
	"\aOP_POST\x10\x00\x12\v\n" +
	"\aOP_LIKE\x10\x01\x12\r\n" +
	"\tOP_DELETE\x10\x02\x12\r\n" +
	"\tOP_UPDATE\x10\x03*L\n" +
	"\tChainRole\x12\x10\n" +
	"\fROLE_UNKNOWN\x10\x00\x12\r\n" +
	"\tROLE_HEAD\x10\x01\x12\x0f\n" +
	"\vROLE_MIDDLE\x10\x02\x12\r\n" +
	"\tROLE_TAIL\x10\x032\xcd\x06\n" +
	"\fMessageBoard\x12G\n" +
	"\n" +
	"CreateUser\x12\".razpravljalnica.CreateUserRequest\x1a\x15.razpravljalnica.User\x12J\n" +
	"\vCreateTopic\x12#.razpravljalnica.CreateTopicRequest\x1a\x16.razpravljalnica.Topic\x12L\n" +
	"\vPostMessage\x12#.razpravljalnica.PostMessageRequest\x1a\x18.razpravljalnica.Message\x12P\n" +
	"\rUpdateMessage\x12%.razpravljalnica.UpdateMessageRequest\x1a\x18.razpravljalnica.Message\x12N\n" +
	"\rDeleteMessage\x12%.razpravljalnica.DeleteMessageRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vLikeMessage\x12#.razpravljalnica.LikeMessageRequest\x1a\x18.razpravljalnica.Message\x12j\n" +
	"\x13GetSubscriptionNode\x12(.razpravljalnica.SubscriptionNodeRequest\x1a).razpravljalnica.SubscriptionNodeResponse\x12I\n" +
	"\n" +
	"ListTopics\x12\x16.google.protobuf.Empty\x1a#.razpravljalnica.ListTopicsResponse\x12X\n" +
	"\vGetMessages\x12#.razpravljalnica.GetMessagesRequest\x1a$.razpravljalnica.GetMessagesResponse\x12Y\n" +
	"\x0eSubscribeTopic\x12&.razpravljalnica.SubscribeTopicRequest\x1a\x1d.razpravljalnica.MessageEvent0\x012\xd1\x03\n" +
	"\fControlPlane\x12S\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a(.razpravljalnica.GetClusterStateResponse\x12j\n" +
	"\x11WatchClusterState\x12).razpravljalnica.WatchClusterStateRequest\x1a(.razpravljalnica.GetClusterStateResponse0\x01\x12R\n" +
	"\tHeartbeat\x12!.razpravljalnica.HeartbeatRequest\x1a\".razpravljalnica.HeartbeatResponse\x12L\n" +
	"\aAddNode\x12\x1f.razpravljalnica.AddNodeRequest\x1a .razpravljalnica.AddNodeResponse\x12^\n" +
	"\fActivateNode\x12$.razpravljalnica.ActivateNodeRequest\x1a(.razpravljalnica.GetClusterStateResponse2\xaa\x02\n" +
	"\vReplication\x12F\n" +
	"\tReplicate\x12!.razpravljalnica.ReplicateRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\x03Ack\x12\x1b.razpravljalnica.AckRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\n" +
	"GetEntries\x12\".razpravljalnica.GetEntriesRequest\x1a#.razpravljalnica.GetEntriesResponse\x12@\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x1b.razpravljalnica.NodeStatusBCZAgithub.com/FilipGjorgjeski/razpravljalnica/protos;razpravljalnicab\x06proto3"

var (
	file_protos_razpravljalnica_proto_rawDescOnce sync.Once
	file_protos_razpravljalnica_proto_rawDescData []byte
)

func file_protos_razpravljalnica_proto_rawDescGZIP() []byte {
	file_protos_razpravljalnica_proto_rawDescOnce.Do(func() {
		file_protos_razpravljalnica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_razpravljalnica_proto_rawDesc), len(file_protos_razpravljalnica_proto_rawDesc)))
	})
	return file_protos_razpravljalnica_proto_rawDescData
}

var file_protos_razpravljalnica_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_razpravljalnica_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_protos_razpravljalnica_proto_goTypes = []any{
	(OpType)(0),                      // 0: razpravljalnica.OpType
	(ChainRole)(0),                   // 1: razpravljalnica.ChainRole
	(*User)(nil),                     // 2: razpravljalnica.User
	(*Topic)(nil),                    // 3: razpravljalnica.Topic
	(*Message)(nil),                  // 4: razpravljalnica.Message
	(*Like)(nil),                     // 5: razpravljalnica.Like
	(*NodeInfo)(nil),                 // 6: razpravljalnica.NodeInfo
	(*CreateUserRequest)(nil),        // 7: razpravljalnica.CreateUserRequest
	(*CreateTopicRequest)(nil),       // 8: razpravljalnica.CreateTopicRequest
	(*PostMessageRequest)(nil),       // 9: razpravljalnica.PostMessageRequest
	(*DeleteMessageRequest)(nil),     // 10: razpravljalnica.DeleteMessageRequest
	(*UpdateMessageRequest)(nil),     // 11: razpravljalnica.UpdateMessageRequest
	(*LikeMessageRequest)(nil),       // 12: razpravljalnica.LikeMessageRequest
	(*ListTopicsResponse)(nil),       // 13: razpravljalnica.ListTopicsResponse
	(*GetMessagesRequest)(nil),       // 14: razpravljalnica.GetMessagesRequest
	(*GetMessagesResponse)(nil),      // 15: razpravljalnica.GetMessagesResponse
	(*SubscribeTopicRequest)(nil),    // 16: razpravljalnica.SubscribeTopicRequest
	(*SubscriptionNodeRequest)(nil),  // 17: razpravljalnica.SubscriptionNodeRequest
	(*SubscriptionNodeResponse)(nil), // 18: razpravljalnica.SubscriptionNodeResponse
	(*MessageEvent)(nil),             // 19: razpravljalnica.MessageEvent
	(*WatchClusterStateRequest)(nil), // 20: razpravljalnica.WatchClusterStateRequest
	(*GetClusterStateResponse)(nil),  // 21: razpravljalnica.GetClusterStateResponse
	(*NodeStatus)(nil),               // 22: razpravljalnica.NodeStatus
	(*HeartbeatRequest)(nil),         // 23: razpravljalnica.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 24: razpravljalnica.HeartbeatResponse
	(*AddNodeRequest)(nil),           // 25: razpravljalnica.AddNodeRequest
	(*AddNodeResponse)(nil),          // 26: razpravljalnica.AddNodeResponse
	(*ActivateNodeRequest)(nil),      // 27: razpravljalnica.ActivateNodeRequest
	(*LogEntry)(nil),                 // 28: razpravljalnica.LogEntry
	(*RegisterSubscriptionOp)(nil),   // 29: razpravljalnica.RegisterSubscriptionOp
	(*CreateUserOp)(nil),             // 30: razpravljalnica.CreateUserOp
	(*CreateTopicOp)(nil),            // 31: razpravljalnica.CreateTopicOp
	(*PostMessageOp)(nil),            // 32: razpravljalnica.PostMessageOp
	(*UpdateMessageOp)(nil),          // 33: razpravljalnica.UpdateMessageOp
	(*DeleteMessageOp)(nil),          // 34: razpravljalnica.DeleteMessageOp
	(*LikeMessageOp)(nil),            // 35: razpravljalnica.LikeMessageOp
	(*ReplicateRequest)(nil),         // 36: razpravljalnica.ReplicateRequest
	(*AckRequest)(nil),               // 37: razpravljalnica.AckRequest
	(*GetEntriesRequest)(nil),        // 38: razpravljalnica.GetEntriesRequest
	(*GetEntriesResponse)(nil),       // 39: razpravljalnica.GetEntriesResponse
	(*timestamppb.Timestamp)(nil),    // 40: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 41: google.protobuf.Empty
}
var file_protos_razpravljalnica_proto_depIdxs = []int32{
	40, // 0: razpravljalnica.Message.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: razpravljalnica.ListTopicsResponse.topics:type_name -> razpravljalnica.Topic
	4,  // 2: razpravljalnica.GetMessagesResponse.messages:type_name -> razpravljalnica.Message
	6,  // 3: razpravljalnica.SubscriptionNodeResponse.node:type_name -> razpravljalnica.NodeInfo
	0,  // 4: razpravljalnica.MessageEvent.op:type_name -> razpravljalnica.OpType
	4,  // 5: razpravljalnica.MessageEvent.message:type_name -> razpravljalnica.Message
	40, // 6: razpravljalnica.MessageEvent.event_at:type_name -> google.protobuf.Timestamp
	6,  // 7: razpravljalnica.GetClusterStateResponse.head:type_name -> razpravljalnica.NodeInfo
	6,  // 8: razpravljalnica.GetClusterStateResponse.tail:type_name -> razpravljalnica.NodeInfo
	6,  // 9: razpravljalnica.GetClusterStateResponse.chain:type_name -> razpravljalnica.NodeInfo
	22, // 10: razpravljalnica.HeartbeatRequest.status:type_name -> razpravljalnica.NodeStatus
	1,  // 11: razpravljalnica.HeartbeatResponse.role:type_name -> razpravljalnica.ChainRole
	6,  // 12: razpravljalnica.HeartbeatResponse.head:type_name -> razpravljalnica.NodeInfo
	6,  // 13: razpravljalnica.HeartbeatResponse.tail:type_name -> razpravljalnica.NodeInfo
	6,  // 14: razpravljalnica.HeartbeatResponse.predecessor:type_name -> razpravljalnica.NodeInfo
	6,  // 15: razpravljalnica.HeartbeatResponse.successor:type_name -> razpravljalnica.NodeInfo
	6,  // 16: razpravljalnica.HeartbeatResponse.chain:type_name -> razpravljalnica.NodeInfo
	6,  // 17: razpravljalnica.AddNodeResponse.current_tail:type_name -> razpravljalnica.NodeInfo
	40, // 18: razpravljalnica.LogEntry.at:type_name -> google.protobuf.Timestamp
	30, // 19: razpravljalnica.LogEntry.create_user:type_name -> razpravljalnica.CreateUserOp
	31, // 20: razpravljalnica.LogEntry.create_topic:type_name -> razpravljalnica.CreateTopicOp
	32, // 21: razpravljalnica.LogEntry.post_message:type_name -> razpravljalnica.PostMessageOp
	33, // 22: razpravljalnica.LogEntry.update_message:type_name -> razpravljalnica.UpdateMessageOp
	34, // 23: razpravljalnica.LogEntry.delete_message:type_name -> razpravljalnica.DeleteMessageOp
	35, // 24: razpravljalnica.LogEntry.like_message:type_name -> razpravljalnica.LikeMessageOp
	29, // 25: razpravljalnica.LogEntry.register_subscription:type_name -> razpravljalnica.RegisterSubscriptionOp
	28, // 26: razpravljalnica.ReplicateRequest.entry:type_name -> razpravljalnica.LogEntry
	28, // 27: razpravljalnica.GetEntriesResponse.entries:type_name -> razpravljalnica.LogEntry
	7,  // 28: razpravljalnica.MessageBoard.CreateUser:input_type -> razpravljalnica.CreateUserRequest
	8,  // 29: razpravljalnica.MessageBoard.CreateTopic:input_type -> razpravljalnica.CreateTopicRequest
	9,  // 30: razpravljalnica.MessageBoard.PostMessage:input_type -> razpravljalnica.PostMessageRequest
	11, // 31: razpravljalnica.MessageBoard.UpdateMessage:input_type -> razpravljalnica.UpdateMessageRequest
	10, // 32: razpravljalnica.MessageBoard.DeleteMessage:input_type -> razpravljalnica.DeleteMessageRequest
	12, // 33: razpravljalnica.MessageBoard.LikeMessage:input_type -> razpravljalnica.LikeMessageRequest
	17, // 34: razpravljalnica.MessageBoard.GetSubscriptionNode:input_type -> razpravljalnica.SubscriptionNodeRequest
	41, // 35: razpravljalnica.MessageBoard.ListTopics:input_type -> google.protobuf.Empty
	14, // 36: razpravljalnica.MessageBoard.GetMessages:input_type -> razpravljalnica.GetMessagesRequest
	16, // 37: razpravljalnica.MessageBoard.SubscribeTopic:input_type -> razpravljalnica.SubscribeTopicRequest
	41, // 38: razpravljalnica.ControlPlane.GetClusterState:input_type -> google.protobuf.Empty
	20, // 39: razpravljalnica.ControlPlane.WatchClusterState:input_type -> razpravljalnica.WatchClusterStateRequest
	23, // 40: razpravljalnica.ControlPlane.Heartbeat:input_type -> razpravljalnica.HeartbeatRequest
	25, // 41: razpravljalnica.ControlPlane.AddNode:input_type -> razpravljalnica.AddNodeRequest
	27, // 42: razpravljalnica.ControlPlane.ActivateNode:input_type -> razpravljalnica.ActivateNodeRequest
	36, // 43: razpravljalnica.Replication.Replicate:input_type -> razpravljalnica.ReplicateRequest
	37, // 44: razpravljalnica.Replication.Ack:input_type -> razpravljalnica.AckRequest
	38, // 45: razpravljalnica.Replication.GetEntries:input_type -> razpravljalnica.GetEntriesRequest
	41, // 46: razpravljalnica.Replication.GetStatus:input_type -> google.protobuf.Empty
	2,  // 47: razpravljalnica.MessageBoard.CreateUser:output_type -> razpravljalnica.User
	3,  // 48: razpravljalnica.MessageBoard.CreateTopic:output_type -> razpravljalnica.Topic
	4,  // 49: razpravljalnica.MessageBoard.PostMessage:output_type -> razpravljalnica.Message
	4,  // 50: razpravljalnica.MessageBoard.UpdateMessage:output_type -> razpravljalnica.Message
	41, // 51: razpravljalnica.MessageBoard.DeleteMessage:output_type -> google.protobuf.Empty
	4,  // 52: razpravljalnica.MessageBoard.LikeMessage:output_type -> razpravljalnica.Message
	18, // 53: razpravljalnica.MessageBoard.GetSubscriptionNode:output_type -> razpravljalnica.SubscriptionNodeResponse
	13, // 54: razpravljalnica.MessageBoard.ListTopics:output_type -> razpravljalnica.ListTopicsResponse
	15, // 55: razpravljalnica.MessageBoard.GetMessages:output_type -> razpravljalnica.GetMessagesResponse
	19, // 56: razpravljalnica.MessageBoard.SubscribeTopic:output_type -> razpravljalnica.MessageEvent
	21, // 57: razpravljalnica.ControlPlane.GetClusterState:output_type -> razpravljalnica.GetClusterStateResponse
	21, // 58: razpravljalnica.ControlPlane.WatchClusterState:output_type -> razpravljalnica.GetClusterStateResponse
	24, // 59: razpravljalnica.ControlPlane.Heartbeat:output_type -> razpravljalnica.HeartbeatResponse
	26, // 60: razpravljalnica.ControlPlane.AddNode:output_type -> razpravljalnica.AddNodeResponse
	21, // 61: razpravljalnica.ControlPlane.ActivateNode:output_type -> razpravljalnica.GetClusterStateResponse
	41, // 62: razpravljalnica.Replication.Replicate:output_type -> google.protobuf.Empty
	41, // 63: razpravljalnica.Replication.Ack:output_type -> google.protobuf.Empty
	39, // 64: razpravljalnica.Replication.GetEntries:output_type -> razpravljalnica.GetEntriesResponse
	22, // 65: razpravljalnica.Replication.GetStatus:output_type -> razpravljalnica.NodeStatus
	47, // [47:66] is the sub-list for method output_type
	28, // [28:47] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_protos_razpravljalnica_proto_init() }
func file_protos_razpravljalnica_proto_init() {
	if File_protos_razpravljalnica_proto != nil {
		return
	}
	file_protos_razpravljalnica_proto_msgTypes[26].OneofWrappers = []any{
		(*LogEntry_CreateUser)(nil),
		(*LogEntry_CreateTopic)(nil),
		(*LogEntry_PostMessage)(nil),
		(*LogEntry_UpdateMessage)(nil),
		(*LogEntry_DeleteMessage)(nil),
		(*LogEntry_LikeMessage)(nil),
		(*LogEntry_RegisterSubscription)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_razpravljalnica_proto_rawDesc), len(file_protos_razpravljalnica_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_protos_razpravljalnica_proto_goTypes,
		DependencyIndexes: file_protos_razpravljalnica_proto_depIdxs,
		EnumInfos:         file_protos_razpravljalnica_proto_enumTypes,
		MessageInfos:      file_protos_razpravljalnica_proto_msgTypes,
	}.Build()
	File_protos_razpravljalnica_proto = out.File
	file_protos_razpravljalnica_proto_goTypes = nil
	file_protos_razpravljalnica_proto_depIdxs = nil
}
